# Tensorflow Introduction

### Tensors

- Every thing in tensorflow is a tensor
- A tensor is basically a set of primitive values shaped into an array of any number of dimensions
- Each tensor has a rank which is the number of dimensions it has

```python

3 # This has a rank of 0
[1, 2, 3] # This has a rank of 1
[ [1, 2, 3], [4, 5, 6] ] # This has a rank of 2

```

### Tensorflow Core Tutorials

In [1]:
import tensorflow as tf

### Sections of a Tensorflow Program

- Building the computational graph
- Running the computational graph


### Computational Graph

- It is a series of tensorflow operations arranged into a graph of nodes.
- Each node takes 0 or more tensors and produces a tensor as an output.

### Constants

+ INPUTS: 0
+ OUTPUS: 1 tensor which it stores internally

In [2]:
nodeA = tf.constant(3.0)
nodeB = tf.constant(4.0)

print (nodeA, nodeB, sep='\n')

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)


### No Output :(

- If you notice the above code, they don't produce any output that we might expect.
- This is because we have only defined a computational graph.
- We haven't run the graph yet

### Sessions

- To actually evaluate a node, we must run the computational graph with the above said operations.
- The sessions encapsulates the control and the state of the tensorflow runtime

#### Sessions where everything has to be defined before it starts

In [3]:
with tf.Session() as sess:
    print('EXPECTED OUTPUT:', sess.run([nodeA, nodeB]))

EXPECTED OUTPUT: [3.0, 4.0]


#### Sessions where we can inline the creation and running of the computational graph

In [4]:
sess1 = tf.InteractiveSession()
print(sess1.run(nodeA + nodeB))
print(sess1.run([nodeA, nodeB]))

7.0
[3.0, 4.0]


### Tensorflow Operations

- Each node in a computational graph takes a tensor as a input and produces a tensor as an output
- These form the operations in tensorflow
- By clubbing operations and tensors we can model complicated computations

Example:

![AddingConstants](https://www.tensorflow.org/images/getting_started_add.png)

In [5]:
nodeC = tf.add(nodeA, nodeB)

print(nodeC, end='\n')

Tensor("Add:0", shape=(), dtype=float32)


In [6]:
with tf.Session() as sess:
    print('RESULT OF A + B:', sess.run([nodeC]))

RESULT OF A + B: [7.0]


### A not so Complex Graph

In [7]:
a = tf.constant(3)
b = tf.constant(5)
c = tf.constant(6)

d = a ** 2 + b * c

print('NOT SO COMPLEX GRAPH:', d)

NOT SO COMPLEX GRAPH: Tensor("add_1:0", shape=(), dtype=int32)


In [8]:
with tf.Session() as sess:
    print('NOT SO COMPLEX GRAPH RESULT:', sess.run(d))

NOT SO COMPLEX GRAPH RESULT: 39


### Tensorflow Placeholders

- A placeholder is a promise to provide a value later

In [9]:
placeholderA = tf.placeholder(tf.float32)
placeholderB = tf.placeholder(tf.float32)

print(placeholderA, placeholderB, sep='\n')

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)


In [10]:
adderNode = placeholderA + placeholderB

print(adderNode)

Tensor("add_2:0", dtype=float32)


In [11]:
with tf.Session() as sess:
    print('ADD:', sess.run(adderNode, {placeholderA: 3, placeholderB: 4}))
    print('ADD:', sess.run(adderNode, {placeholderA: [1, 2], placeholderB: [3, 7]}))

ADD: 7.0
ADD: [ 4.  9.]


##### But what if you want to add multi-dimensional array elements

In [12]:
multiPlaceholderA = tf.placeholder(tf.int32, shape=[None, 2, 2])
multiPlaceholderB = tf.placeholder(tf.int32)

adderNodeMulti = multiPlaceholderA + multiPlaceholderB

with tf.Session() as sess:
    print('ADD MULTI:\n', sess.run(adderNodeMulti, {
        multiPlaceholderA: [
            [[1,2], [3,4]], 
            [[2,3], [4,5]]
        ], multiPlaceholderB: 1}))

ADD MULTI:
 [[[2 3]
  [4 5]]

 [[3 4]
  [5 6]]]


### Variables

- By default constants have their value initialized when the session starts. This is not the case with the variables.
- So we need to initialize them before we use them.

In [13]:
# This will work
constA = tf.constant(1)
constB = tf.constant(2)
constC = constA + constB

with tf.Session() as sess:
    print('CONSTANTS ARE INITIALIZED:', sess.run(constC))

CONSTANTS ARE INITIALIZED: 3


In [14]:
# This will not work
varA = tf.Variable([1.])
varB = tf.Variable([2.])
varC = varA + varB


with tf.Session() as sess:
    try:
        sess.run(varC)
    except:
        print('ERROR:', 'This threw an error because we didn`t initialize a and b')

ERROR: This threw an error because we didn`t initialize a and b


In [15]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    print('OUTPUT:', sess.run(varC))

    print('No Error... :P')

OUTPUT: [ 3.]
No Error... :P


### Simple Linear Model

#### Creation and Running the model

In [16]:
x = tf.placeholder(tf.float32)
b = tf.Variable(.3)
W = tf.Variable(.10)

y = W * x + b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y, {x: [1.,2.,3.,4.]}))

[ 0.40000001  0.5         0.60000002  0.70000005]


#### Find out how good the model is

- A loss measures how far apart the current model is from the provided data.

In [17]:
y_actual = tf.placeholder(tf.float32)

loss = tf.reduce_sum(tf.square(y_actual - y))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(loss, {x: [1,2,3,4], y_actual: [2,4,6,8]}))

97.26


### Fix the model

In [18]:
fixW = tf.assign(W, 2)
fixb = tf.assign(b, 0)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run([fixW, fixb])
    print(sess.run(loss, {x: [1,2,3,4], y_actual: [2,4,6,8]}))

0.0
